name: hv-landsat-cookbook-dev
channels:
  - conda-forge
dependencies:
  - holoviews
  - hvplot
  - panel
  - geoviews
  - datashader
  - jupyter-book
  - jupyterlab
  - pip
  - pip:
      - sphinx-pythia-theme
