# create this environment with `conda env create`, not `conda create`, 
# otherwise nodefaults will be ignored -_-

name: hv-landsat-cookbook
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - holoviews
  - hvplot
  - panel
  - geoviews
  - datashader
  - colorcet
  - intake
  - intake-xarray
  - xarray
  - bokeh
  - dask
  - dask-ml
  - pandas
  - numpy
  - cartopy
  - rasterio
  - s3fs
  - jupyter-book
  - jupyterlab
  - satsearch
  - intake-stac
  - pip
  - pip:
      - sphinx-pythia-theme
