name: landsat-ml-cookbook
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - shapely<2.0.0
  - ipykernel
  - hvplot
  - panel
  - geoviews
  - datashader
  - colorcet
  - intake
  - intake-xarray
  - xarray
  - bokeh
  - dask
  - dask-ml
  - pandas
  - numpy
  - cartopy
  - rasterio
  - s3fs
  - jupyter-book
  - jupyterlab
  - intake-stac
  - pip
  - pip:
      - sphinx-pythia-theme
