name: landsat-ml-cookbook
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python=3.10
  - shapely<2.0.0
  - pandas
  - xarray-datatree
  - planetary-computer
  - pystac
  - pystac-client
  - odc-stac
  - ipykernel
  - hvplot
  - panel
  - geoviews
  - datashader
  - colorcet
  - intake
  - intake-xarray
  - xarray
  - bokeh
  - dask
  - dask-ml
  - pandas
  - numpy
  - cartopy
  - rasterio
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - pip:
      - sphinx-pythia-theme
